name: Install Terraform on agent
trigger:
  - UAT

parameters:
- name: createdestroy
  type: string 
  default: 'apply'

- name: poolname
  type: string 
  default: 'Azure Pipelines'

stages:
- stage: Install_Terraform  
  jobs:
  - job: Install_Terraform 
    displayName: Agent job 1
    pool:
      name: ${{ parameters.poolname }}
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
      

- stage: Infra_Pre_Validate_Tf
  jobs:
  - job: Infra_Pre_Validate_Tf
    displayName: Infra_Pre_Validate_Tf
    pool:
      #name: Azure Pipelines
      name: ${{ parameters.poolname }}
    steps:
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV4@4
      displayName: Init
      inputs:
        backendServiceArm: 'vcl-SP-conn'
        backendAzureRmResourceGroupName: 'docker-app-vishwa_group'
        backendAzureRmStorageAccountName: vishwa2024tfstate
        backendAzureRmContainerName: tfstatefiles
        backendAzureRmKey: uat-vm-agent.tfstate
        workingDirectory: $(Build.SourcesDirectory)/infra-pre-requiste-tf
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV4@4
      displayName: validate
      inputs:
        command: validate
        environmentServiceNameAzureRM: 'vcl-SP-conn'
        workingDirectory: $(Build.SourcesDirectory)/infra-pre-requiste-tf

- stage: Infra_Pre_Apply_Tf
  dependsOn: Infra_Pre_Validate_Tf
  jobs:
  - job: Infra_Pre_Apply_Tf
    displayName: Job_3
    #timeoutInMinutes: 5
    pool:
      #name: Azure Pipelines
      name: ${{ parameters.poolname }}    
    steps:
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV4@4
      displayName: Init
      inputs:
        backendServiceArm: 'vcl-SP-conn'
        backendAzureRmResourceGroupName: 'docker-app-vishwa_group'
        backendAzureRmStorageAccountName: vishwa2024tfstate
        backendAzureRmContainerName: tfstatefiles
        backendAzureRmKey: uat-vm-agent.tfstate
        workingDirectory: $(Build.SourcesDirectory)/infra-pre-requiste-tf

    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV4@4
      displayName: Plan
      inputs:
        command: plan
        #commandOptions: '-var client_id=${{ parameters.clients_id }}  -var client_secret=${{ parameters.clients_secret }}'
        environmentServiceNameAzureRM: 'vcl-SP-conn'
        workingDirectory: $(Build.SourcesDirectory)/infra-pre-requiste-tf

    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV4@4
      displayName: Apply Or Destroy
      inputs:
        command: ${{ parameters.createdestroy }}
        #commandOptions: '-var client_id=${{ parameters.clients_id }}  -var client_secret=${{ parameters.clients_secret }}'
        environmentServiceNameAzureRM: 'vcl-SP-conn'
        workingDirectory: $(Build.SourcesDirectory)/infra-pre-requiste-tf
